// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiODeSrn68x3OALkCYs97Yvj4FRMsDtg',
    appId: '1:335848098890:web:a49b7002ba66eee1e0aab3',
    messagingSenderId: '335848098890',
    projectId: 'musafir-app-mobile',
    authDomain: 'musafir-app-mobile.firebaseapp.com',
    storageBucket: 'musafir-app-mobile.appspot.com',
    measurementId: 'G-9QSHY5M4Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3HICu_uZx-NDESAqPOtIsKLpnT-DNSE',
    appId: '1:335848098890:android:9380ae985b3fbe02e0aab3',
    messagingSenderId: '335848098890',
    projectId: 'musafir-app-mobile',
    storageBucket: 'musafir-app-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAgg_4Wrs1kCKlmlQvk772sLTNlBI7bMc',
    appId: '1:335848098890:ios:154462accf15d2c9e0aab3',
    messagingSenderId: '335848098890',
    projectId: 'musafir-app-mobile',
    storageBucket: 'musafir-app-mobile.appspot.com',
    iosClientId: '335848098890-ovmha65killbn1o3npd6417pbsr6abti.apps.googleusercontent.com',
    iosBundleId: 'com.example.musafirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAgg_4Wrs1kCKlmlQvk772sLTNlBI7bMc',
    appId: '1:335848098890:ios:154462accf15d2c9e0aab3',
    messagingSenderId: '335848098890',
    projectId: 'musafir-app-mobile',
    storageBucket: 'musafir-app-mobile.appspot.com',
    iosClientId: '335848098890-ovmha65killbn1o3npd6417pbsr6abti.apps.googleusercontent.com',
    iosBundleId: 'com.example.musafirApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCiODeSrn68x3OALkCYs97Yvj4FRMsDtg',
    appId: '1:335848098890:web:6d84117278153132e0aab3',
    messagingSenderId: '335848098890',
    projectId: 'musafir-app-mobile',
    authDomain: 'musafir-app-mobile.firebaseapp.com',
    storageBucket: 'musafir-app-mobile.appspot.com',
    measurementId: 'G-9FM946DWE3',
  );

}