// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjto31wabWAxZZE2NJhYcxgo_rIDQbPuw',
    appId: '1:302306254082:web:979040727f730c6aaa761b',
    messagingSenderId: '302306254082',
    projectId: 'demoflutter-65620',
    authDomain: 'demoflutter-65620.firebaseapp.com',
    storageBucket: 'demoflutter-65620.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJ7IM90OzTf7u3Nw1ZnOAI-wjqGio7Gw',
    appId: '1:302306254082:android:20f41be12506312faa761b',
    messagingSenderId: '302306254082',
    projectId: 'demoflutter-65620',
    storageBucket: 'demoflutter-65620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfhba3lrP_k4Uya8MmMPrMXohqWA2Ais0',
    appId: '1:302306254082:ios:99f6fefc606e61e4aa761b',
    messagingSenderId: '302306254082',
    projectId: 'demoflutter-65620',
    storageBucket: 'demoflutter-65620.appspot.com',
    iosBundleId: 'com.example.musafirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfhba3lrP_k4Uya8MmMPrMXohqWA2Ais0',
    appId: '1:302306254082:ios:efc8459b75d4b31aaa761b',
    messagingSenderId: '302306254082',
    projectId: 'demoflutter-65620',
    storageBucket: 'demoflutter-65620.appspot.com',
    iosBundleId: 'com.example.musafirApp.RunnerTests',
  );
}
